//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BugNET.Entities.DataContext
{
    public partial class CustomFieldSelection
    {
        public Guid Id { get; set; }
        public Guid CustomFieldId { get; set; }
        public string Value { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
    
        public virtual CustomField CustomField { get; set; }
    }
    
}
