//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BugNET.Entities.DataContext
{
    public partial class Issue
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public Nullable<System.Guid> PriorityId { get; set; }
        public Nullable<System.Guid> TypeId { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public System.Guid ProjectId { get; set; }
        public Nullable<System.Guid> AffectedMilestoneId { get; set; }
        public Nullable<System.Guid> ResolutionId { get; set; }
        public System.Guid CreatorUserId { get; set; }
        public Nullable<System.Guid> AssignedUserId { get; set; }
        public Nullable<System.Guid> OwnerUserId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public System.Guid MilestoneId { get; set; }
        public int Visibility { get; set; }
        public decimal Estimation { get; set; }
        public int Progress { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public System.Guid LastUpdateUserId { get; set; }
        public bool Disabled { get; set; }
    
        public virtual ProjectCategory ProjectCategory { get; set; }
        public virtual IssueType IssueType { get; set; }
        public virtual Milestone Milestone { get; set; }
        public virtual Milestone AffectedMilestone { get; set; }
        public virtual Priority BugNet_ProjectPriorities { get; set; }
        public virtual Resolution Resolution { get; set; }
        public virtual Project Project { get; set; }
        public virtual Status Status { get; set; }
    }
    
}
