//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BugNET.Entities.DataContext
{
    public partial class ProjectMailBox
    {
        public System.Guid Id { get; set; }
        public string MailBox { get; set; }
        public System.Guid ProjectId { get; set; }
        public Nullable<System.Guid> AssignToUserId { get; set; }
        public Nullable<int> IssueTypeId { get; set; }
    
        public virtual Project Project { get; set; }
    }
    
}
