//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BugNET.Entities.DataContext
{
    public partial class ProjectIssueField
    {
        public System.Guid ld { get; set; }
        public System.Guid ProjectId { get; set; }
        public string IssueFieldId { get; set; }
        public bool IssueFieldRequired { get; set; }
        public bool IssueFieldShowOnNewIssue { get; set; }
        public bool IssueFieldShowOnEditIssue { get; set; }
        public int SortOrder { get; set; }
    
        public virtual Project Project { get; set; }
    }
    
}
