//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BugNET.Entities.DataContext
{
    public partial class Project
    {
        public Project()
        {
            this.Issues = new HashSet<Issue>();
            this.Categories = new HashSet<ProjectCategory>();
            this.CustomFields = new HashSet<CustomField>();
            this.IssueFields = new HashSet<ProjectIssueField>();
            this.IssueTypes = new HashSet<IssueType>();
            this.MailBoxes = new HashSet<ProjectMailBox>();
            this.Milestones = new HashSet<Milestone>();
            this.Notifications = new HashSet<ProjectNotification>();
            this.Priorities = new HashSet<Priority>();
            this.ProjectStatus = new HashSet<Status>();
            this.Queries = new HashSet<Query>();
            this.Roles = new HashSet<Role>();
            this.UserProjects = new HashSet<UserProject>();
        }
    
        public System.Guid Id { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectDescription { get; set; }
        public string AttachmentUploadPath { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool ProjectDisabled { get; set; }
        public int ProjectAccessType { get; set; }
        public System.Guid ProjectManagerUserId { get; set; }
        public System.Guid ProjectCreatorUserId { get; set; }
        public bool AllowAttachments { get; set; }
        public Nullable<int> AttachmentStorageType { get; set; }
        public string SvnRepositoryUrl { get; set; }
        public bool AllowIssueVoting { get; set; }
        public byte[] ProjectImageFileContent { get; set; }
        public string ProjectImageFileName { get; set; }
        public string ProjectImageContentType { get; set; }
        public Nullable<long> ProjectImageFileSize { get; set; }
    
        public virtual ICollection<Issue> Issues { get; set; }
        public virtual ICollection<ProjectCategory> Categories { get; set; }
        public virtual ICollection<CustomField> CustomFields { get; set; }
        public virtual ICollection<ProjectIssueField> IssueFields { get; set; }
        public virtual ICollection<IssueType> IssueTypes { get; set; }
        public virtual ICollection<ProjectMailBox> MailBoxes { get; set; }
        public virtual ICollection<Milestone> Milestones { get; set; }
        public virtual ICollection<ProjectNotification> Notifications { get; set; }
        public virtual ICollection<Priority> Priorities { get; set; }
        public virtual Resolution Resolutions { get; set; }
        public virtual ICollection<Status> ProjectStatus { get; set; }
        public virtual ICollection<Query> Queries { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<UserProject> UserProjects { get; set; }
    }
    
}
