//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BugNET.Entities.DataContext
{
    public partial class RelatedIssue
    {
        public Guid PrimaryIssueId { get; set; }
        public Guid SecondaryIssueId { get; set; }
        public int RelationType { get; set; }
    }
    
}
