//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BugNET.Entities.DataContext
{
    public partial class UserProfile
    {
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> IssuesPageSize { get; set; }
        public string NotificationTypes { get; set; }
        public string PreferredLocale { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string SelectedIssueColumns { get; set; }
    }
    
}
