//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BugNET.Entities.DataContext
{
    public partial class UserRole
    {
        public System.Guid UserId { get; set; }
        public System.Guid RoleId { get; set; }
    
        public virtual Role Role { get; set; }
    }
    
}
